coverage:
  status:
    patch: false
    project:
      default:
        threshold: 0.1%
  range: 30..60

ignore:
  - "test"
  - "third_party"
  - "source/util.cpp"
  - "include/LuaBridge"

comment:
  require_changes: true