name: Standalone

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: pull submodule
      run: git submodule update --init --recursive
    
    - name: configure
      run: cmake -Hstandalone -Bbuild

    - name: build
      run: cmake --build build -j4
